### ISSUE TITLE
#11 cart vuole un exception

### ISSUE THREAD

**Issue by ilGrandeWorro** [develhope/Java23-Team2-Warehouse#13]
https://github.com/develhope/Java23-Team2-Warehouse/blob/247dd42ea0e95b0b666d813b27c78514ee3143be/src/classes/Cart.java#L86

86:29
java: unreported exception java.lang.Exception; must be caught or declared to be thrown

Richiede un exception

**Comment by Calyen93** [comment]
risolto nella nuova pull request
